(cl:defpackage biotac_sp_ros-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "BADTWOINTS"
   "<BADTWOINTS-REQUEST>"
   "BADTWOINTS-REQUEST"
   "<BADTWOINTS-RESPONSE>"
   "BADTWOINTS-RESPONSE"
  ))

