// Generated by gencpp from file biotac_sp_ros/AddTwoInts.msg
// DO NOT EDIT!


#ifndef BIOTAC_SP_ROS_MESSAGE_ADDTWOINTS_H
#define BIOTAC_SP_ROS_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <biotac_sp_ros/AddTwoIntsRequest.h>
#include <biotac_sp_ros/AddTwoIntsResponse.h>


namespace biotac_sp_ros
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace biotac_sp_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::biotac_sp_ros::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::biotac_sp_ros::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::biotac_sp_ros::AddTwoInts > {
  static const char* value()
  {
    return "biotac_sp_ros/AddTwoInts";
  }

  static const char* value(const ::biotac_sp_ros::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::biotac_sp_ros::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::biotac_sp_ros::AddTwoInts >
template<>
struct MD5Sum< ::biotac_sp_ros::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::biotac_sp_ros::AddTwoInts >::value();
  }
  static const char* value(const ::biotac_sp_ros::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::biotac_sp_ros::AddTwoIntsRequest> should match
// service_traits::DataType< ::biotac_sp_ros::AddTwoInts >
template<>
struct DataType< ::biotac_sp_ros::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::biotac_sp_ros::AddTwoInts >::value();
  }
  static const char* value(const ::biotac_sp_ros::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::biotac_sp_ros::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::biotac_sp_ros::AddTwoInts >
template<>
struct MD5Sum< ::biotac_sp_ros::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::biotac_sp_ros::AddTwoInts >::value();
  }
  static const char* value(const ::biotac_sp_ros::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::biotac_sp_ros::AddTwoIntsResponse> should match
// service_traits::DataType< ::biotac_sp_ros::AddTwoInts >
template<>
struct DataType< ::biotac_sp_ros::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::biotac_sp_ros::AddTwoInts >::value();
  }
  static const char* value(const ::biotac_sp_ros::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BIOTAC_SP_ROS_MESSAGE_ADDTWOINTS_H
