// Generated by gencpp from file biotac_sp_ros/BadTwoInts.msg
// DO NOT EDIT!


#ifndef BIOTAC_SP_ROS_MESSAGE_BADTWOINTS_H
#define BIOTAC_SP_ROS_MESSAGE_BADTWOINTS_H

#include <ros/service_traits.h>


#include <biotac_sp_ros/BadTwoIntsRequest.h>
#include <biotac_sp_ros/BadTwoIntsResponse.h>


namespace biotac_sp_ros
{

struct BadTwoInts
{

typedef BadTwoIntsRequest Request;
typedef BadTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BadTwoInts
} // namespace biotac_sp_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::biotac_sp_ros::BadTwoInts > {
  static const char* value()
  {
    return "60962375a49bd6746d7c85dff75ebb9c";
  }

  static const char* value(const ::biotac_sp_ros::BadTwoInts&) { return value(); }
};

template<>
struct DataType< ::biotac_sp_ros::BadTwoInts > {
  static const char* value()
  {
    return "biotac_sp_ros/BadTwoInts";
  }

  static const char* value(const ::biotac_sp_ros::BadTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::biotac_sp_ros::BadTwoIntsRequest> should match
// service_traits::MD5Sum< ::biotac_sp_ros::BadTwoInts >
template<>
struct MD5Sum< ::biotac_sp_ros::BadTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::biotac_sp_ros::BadTwoInts >::value();
  }
  static const char* value(const ::biotac_sp_ros::BadTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::biotac_sp_ros::BadTwoIntsRequest> should match
// service_traits::DataType< ::biotac_sp_ros::BadTwoInts >
template<>
struct DataType< ::biotac_sp_ros::BadTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::biotac_sp_ros::BadTwoInts >::value();
  }
  static const char* value(const ::biotac_sp_ros::BadTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::biotac_sp_ros::BadTwoIntsResponse> should match
// service_traits::MD5Sum< ::biotac_sp_ros::BadTwoInts >
template<>
struct MD5Sum< ::biotac_sp_ros::BadTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::biotac_sp_ros::BadTwoInts >::value();
  }
  static const char* value(const ::biotac_sp_ros::BadTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::biotac_sp_ros::BadTwoIntsResponse> should match
// service_traits::DataType< ::biotac_sp_ros::BadTwoInts >
template<>
struct DataType< ::biotac_sp_ros::BadTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::biotac_sp_ros::BadTwoInts >::value();
  }
  static const char* value(const ::biotac_sp_ros::BadTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BIOTAC_SP_ROS_MESSAGE_BADTWOINTS_H
