# CMake generated Testfile for 
# Source directory: /home/pi/ros_catkin_ws/src/rospack/test
# Build directory: /home/pi/ros_catkin_ws/build_isolated/rospack/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_rospack_gtest_rospack-utest "/home/pi/ros_catkin_ws/build_isolated/rospack/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/pi/ros_catkin_ws/build_isolated/rospack/test_results/rospack/gtest-rospack-utest.xml" "--working-dir" "/home/pi/ros_catkin_ws/build_isolated/rospack/test" "--return-code" "/home/pi/ros_catkin_ws/devel_isolated/rospack/lib/rospack/rospack-utest --gtest_output=xml:/home/pi/ros_catkin_ws/build_isolated/rospack/test_results/rospack/gtest-rospack-utest.xml")
set_tests_properties(_ctest_rospack_gtest_rospack-utest PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/melodic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/pi/ros_catkin_ws/src/rospack/test/CMakeLists.txt;2;catkin_add_gtest;/home/pi/ros_catkin_ws/src/rospack/test/CMakeLists.txt;0;")
add_test(_ctest_rospack_nosetests_test.test "/home/pi/ros_catkin_ws/build_isolated/rospack/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/melodic/share/catkin/cmake/test/run_tests.py" "/home/pi/ros_catkin_ws/build_isolated/rospack/test_results/rospack/nosetests-test.test.xml" "--working-dir" "/home/pi/ros_catkin_ws/build_isolated/rospack/test/test" "--return-code" "\"/usr/bin/cmake\" -E make_directory /home/pi/ros_catkin_ws/build_isolated/rospack/test_results/rospack" "/usr/bin/nosetests-2.7 -P --process-timeout=60 --where=/home/pi/ros_catkin_ws/build_isolated/rospack/test/test --with-xunit --xunit-file=/home/pi/ros_catkin_ws/build_isolated/rospack/test_results/rospack/nosetests-test.test.xml")
set_tests_properties(_ctest_rospack_nosetests_test.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/melodic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/melodic/share/catkin/cmake/test/nosetests.cmake;83;catkin_run_tests_target;/home/pi/ros_catkin_ws/src/rospack/test/CMakeLists.txt;21;catkin_add_nosetests;/home/pi/ros_catkin_ws/src/rospack/test/CMakeLists.txt;0;")
